//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticasEscuelaFrontEnd.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.alumno_x_curso = new HashSet<alumno_x_curso>();
            this.nota = new HashSet<nota>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Legajo { get; set; }
        public string Dni { get; set; }
        public string Descripcion { get; set; }
        public bool Habilitado { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<alumno_x_curso> alumno_x_curso { get; set; }
        public virtual ICollection<nota> nota { get; set; }
    }
}
