//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticasEscuelaFrontEnd.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public curso()
        {
            this.alumno_x_curso = new HashSet<alumno_x_curso>();
            this.materia_x_curso = new HashSet<materia_x_curso>();
        }
    
        public int Id { get; set; }
        public int Anio { get; set; }
        public int Division { get; set; }
        public bool Habilitado { get; set; }
        public int IdEspecialidad { get; set; }
        public int IdTurno { get; set; }
    
        public virtual ICollection<alumno_x_curso> alumno_x_curso { get; set; }
        public virtual especialidad especialidad { get; set; }
        public virtual turno turno { get; set; }
        public virtual ICollection<materia_x_curso> materia_x_curso { get; set; }
    }
}
