//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticasEscuelaFrontEnd.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_x_curso
    {
        public materia_x_curso()
        {
            this.nota = new HashSet<nota>();
        }
    
        public int Id { get; set; }
        public int IdMateria { get; set; }
        public int IdCurso { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual materia materia { get; set; }
        public virtual ICollection<nota> nota { get; set; }
    }
}
