//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticasEscuelaFrontEnd.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int Id { get; set; }
        public Nullable<sbyte> Nota1erTrim { get; set; }
        public Nullable<sbyte> Nota2doTrim { get; set; }
        public Nullable<sbyte> Nota3erTrim { get; set; }
        public Nullable<sbyte> NotaDefinitiva { get; set; }
        public Nullable<float> NotaFinal { get; set; }
        public int IdAlumno { get; set; }
        public int IdMateriaCurso { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual materia_x_curso materia_x_curso { get; set; }
    }
}
