//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticasEscuelaFrontEnd.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.alumno = new HashSet<alumno>();
            this.docente = new HashSet<docente>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Contrasenia { get; set; }
        public bool Habilitado { get; set; }
        public int IdRol { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
        public virtual ICollection<docente> docente { get; set; }
        public virtual rol rol { get; set; }
    }
}
